services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile

    container_name: web
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ob-web-data:/var/lib/odoo
      - ./config:/etc/odoo
    environment:
      - PASSWORD_FILE=odoo
      - HOST=db
      - USER=odoo
  db:
    image: postgres:15
    container_name: db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ob-db-data:/var/lib/postgresql/data/pgdata
volumes:
  ob-web-data:
  ob-db-data:
